// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Aug  6 23:07:27 2010

#include <wx/wx.h>
#include <wx/image.h>
#include "MyFrame.h"



class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    wxInitAllImageHandlers();
    MyFrame* frame_1 = new MyFrame(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(frame_1);
    frame_1->Show();
    return true;
}
