// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Aug  6 23:07:27 2010

#include <wx/wx.h>
#include <wx/image.h>
#include "cv.h"
#include "highgui.h"


#ifndef MYFRAME_H
#define MYFRAME_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxMenuBar* frame_1_menubar;
    wxStatusBar* frame_1_statusbar;
    wxToolBar* frame_1_toolbar;
    wxStaticBitmap* bitmap_1;
    wxStaticLine* static_line_1;
    wxStaticText* label_1;
    wxSlider* sliderFramenum;
    wxStaticText* label_2;
    wxSlider* sliderFramenum_copy;
    wxStaticText* label_3;
    wxSlider* sliderFramenum_copy_1;
    wxStaticText* label_4;
    wxSlider* sliderFramenum_copy_2;
    wxPanel* panel_1;
    // end wxGlade
}; // wxGlade: end class


#endif // MYFRAME_H
