// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Aug  6 23:07:27 2010

#include "MyFrame.h"
#include <iostream>

// begin wxGlade: ::extracode

// end wxGlade


MyFrame::MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    panel_1 = new wxPanel(this, wxID_ANY);
    frame_1_menubar = new wxMenuBar();
    SetMenuBar(frame_1_menubar);
    frame_1_statusbar = CreateStatusBar(1, 0);
    frame_1_toolbar = new wxToolBar(this, -1);
    SetToolBar(frame_1_toolbar);
    frame_1_toolbar->Realize();
    bitmap_1 = new wxStaticBitmap(panel_1, wxID_ANY, wxNullBitmap);
    static_line_1 = new wxStaticLine(panel_1, wxID_ANY);
    label_1 = new wxStaticText(panel_1, wxID_ANY, wxT("Frame number:"));
    sliderFramenum = new wxSlider(panel_1, wxID_ANY, 0, 0, 256, wxDefaultPosition, wxDefaultSize, wxSL_HORIZONTAL|wxSL_AUTOTICKS|wxSL_LABELS);
    label_2 = new wxStaticText(panel_1, wxID_ANY, wxT("Threshold:"));
    sliderFramenum_copy = new wxSlider(panel_1, wxID_ANY, 0, 0, 10, wxDefaultPosition, wxDefaultSize, wxSL_HORIZONTAL|wxSL_AUTOTICKS|wxSL_LABELS);
    label_3 = new wxStaticText(panel_1, wxID_ANY, wxT("Base left:"));
    sliderFramenum_copy_1 = new wxSlider(panel_1, wxID_ANY, 0, 0, 10, wxDefaultPosition, wxDefaultSize, wxSL_HORIZONTAL|wxSL_AUTOTICKS|wxSL_LABELS);
    label_4 = new wxStaticText(panel_1, wxID_ANY, wxT("Base right:"));
    sliderFramenum_copy_2 = new wxSlider(panel_1, wxID_ANY, 0, 0, 10, wxDefaultPosition, wxDefaultSize, wxSL_HORIZONTAL|wxSL_AUTOTICKS|wxSL_LABELS);

    set_properties();
    do_layout();
    // end wxGlade

    cv::Mat img = cv::imread("lena.jpg");
    wxImage plot(img.cols, img.rows, (unsigned char*) img.data, true);
    wxBitmap bm(plot);

    bitmap_1->SetClientSize(img.cols,img.rows);
    bitmap_1->SetBitmap(bm);
}


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("ContactAngle"));
    int frame_1_statusbar_widths[] = { -1 };
    frame_1_statusbar->SetStatusWidths(1, frame_1_statusbar_widths);
    const wxString frame_1_statusbar_fields[] = {
        wxT("frame_1_statusbar")
    };
    for(int i = 0; i < frame_1_statusbar->GetFieldsCount(); ++i) {
        frame_1_statusbar->SetStatusText(frame_1_statusbar_fields[i], i);
    }
    bitmap_1->SetMinSize(wxSize(640,480));
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(bitmap_1, 1, wxALL|wxEXPAND, 0);
    sizer_2->Add(static_line_1, 0, wxEXPAND, 0);
    sizer_3->Add(label_1, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_3->Add(sliderFramenum, 5, wxALL|wxEXPAND, 0);
    sizer_2->Add(sizer_3, 0, wxEXPAND, 0);
    sizer_4->Add(label_2, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_4->Add(sliderFramenum_copy, 1, wxALL|wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    sizer_2->Add(sizer_4, 0, wxEXPAND, 0);
    sizer_5->Add(label_3, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_5->Add(sliderFramenum_copy_1, 1, wxALL|wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    sizer_2->Add(sizer_5, 0, wxEXPAND, 0);
    sizer_6->Add(label_4, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_6->Add(sliderFramenum_copy_2, 1, wxALL|wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    sizer_2->Add(sizer_6, 0, wxEXPAND, 0);
    panel_1->SetSizer(sizer_2);
    sizer_1->Add(panel_1, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

