#+TITLE: Building from source

* Prerequisites

Apart form the source code, you will need the [[http://opencv.willowgarage.com][OpenCV]] library, the
[[http://www.wxwidgets.org][wxWidgets]] toolkit, the [[http://cmake.org][cmake]] build system and a working C++ compiler.

On an e.g. Debian or Ubuntu, the following should do the job:

#+BEGIN_EXAMPLE
apt-get install build-essential cmake libcv-dev libcvaux-dev libhighgui-dev libwxgtk2.8-dev   
#+END_EXAMPLE

On Windows, you can get the libraries precompiled from their
corresponding websites and you can use e.g. the free Microsoft Visual
Studio 2008 (or 2010) Express. If you want to also build a Windows
Installer, you will also need the free [[http://nsis.sourceforge.net/Main_Page][NSIS Installer]].

* Get the source code

The source code is in a git repository hosted on sourceforge which can
be browsed via [[http://contactangle.git.sourceforge.net/][GitWeb]]. You can check it out with the following (e.g. on
a Unix-like system):

#+BEGIN_EXAMPLE
git clone git://contactangle.git.sourceforge.net/gitroot/contactangle/contactangle
#+END_EXAMPLE

* Build on Unix

In the source directory run the following:

#+BEGIN_EXAMPLE
cmake .
make
sudo make install
#+END_EXAMPLE

* Build on Windows

Open cmake-gui, set the source and build directory to the ContacAngle
source dir, press configure (for eg. Visual Studio), press generate.

Open the generated ContactAngle.sln in Visual Studio, build
solution. This will give you the binary in the Release. or Debug/
directory, depending on your build configuration. 
