(add-to-list 'load-path "~/.emacs-files/org/")
(require 'org-install)
(add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
(setq org-export-with-LaTeX-fragments t)
(setq org-export-html-inline-images t)
(setq user-mail-address "daniel.gruber@tydirium.org")
(setq org-export-with-toc nil)
(setq org-export-author-info nil)
(setq org-export-creator-info nil)
(setq org-export-html-style "<link rel=\"stylesheet\" type=\"text/css\" href=\"default.css\">")
(setq org-export-time-stamp-file nil)
(setq org-export-with-timestamps nil)
 
